### ISSUE TITLE
Apply button low contrast

### ISSUE THREAD

**Issue by EinarBalan** [uclaacm/hoth.uclaacm.com#234] opened 2022-02-18 20:57 UTC
Not sure if this was present before, but Christina and I just noticed that the apply button has super low contrast, screenshot below
<img width="116" alt="Screen Shot 2022-02-18 at 12 57 13 PM" src="https://user-images.githubusercontent.com/40647794/154760151-fb33d26d-84e5-42d4-82f3-79e6983e5eeb.png">

Can we change the text to be white?

**Comment by TimothyGu** [comment] 2022-02-19 02:54
Duplicate of #229.

**Closed by TimothyGu** 2022-02-19 02:54 UTC
